// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  camp_information: dynamic(() => import('./CampInformation')),
  event: dynamic(() => import('./Events')),
  experience: dynamic(() => import('./Experience')),
  faq: dynamic(() => import('./Faq')),
  more_details: dynamic(() => import('./MoreDetails')),
}
